--DAY_3
--02-01-2026
--TOPIC. IN,NOT IN,LIKE('%','_'WILDCARD CHARECTERS)OPRETERS.
--1)WAQD EMPLOYEES TO DISPLOYEES DEPARTMENT 30,40,50
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(30,40,50);

--2)WAQD TO EMPLOYEES WHERE DEPARTMENT_ID 80,90,100 WITHOUT USING IN OPREATER
SELECT * 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID =80
OR DEPARTMENT_ID=90
OR DEPARTMENT_ID=100;

--3)WAQD EMPLOYEES THERE SALARY >7000 AND DEPARTMENT ID NOT EQUAL TO 30,40,50.
SELECT * 
FROM EMPLOYEES
WHERE SALARY > 7000
AND DEPARTMENT_ID NOT IN(30,40,50); 
 
--4)WAQD EMPLOYEES THOSE DEPARTMENT ID 20,40,80 AND THERE FIRST NAME START WITH P.
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (20,30,40)
AND FIRST_NAME LIKE 'P%';
 
--5)WAQD DEPARTMENT_NAME WHOSE DEPARTMENT_ID IS 100,20 AND SALARY NOT EQUAL TO 7000
SELECT *
FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN (100,20)
AND SALARY <> 7000;
 
--6)WQAD JOB_ID IS NOT EQUAL TO IT_PROG AND AD_VP AND HAVING SALARY IS GREATER THAN 8000.
SELECT * 
FROM EMPLOYEES
WHERE JOB_ID NOT IN ('IT_PROG','AD_VP')
AND SALARY > 8000;

--7)WAQD DETAILS OF EMPLOYEES WHOSE JOB_ID START WITH 'I' CHAREACTER AND THOSE SALARY LESS THAH 10000.
SELECT * 
FROM EMPLOYEES 
WHERE JOB_ID LIKE 'I%'
AND SALARY < 10000;

--8)WAQD EMPLOYEES DETAILS WHOSE FIST NAME START WITH 'A' AND TOTAL NUMBER OF CHARETER IS 7.
SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A______';
 
--9)WAQD EMPLOYEES WHOSE GET SALARY GREATER THAN 2000 AND NAME CONTENT 'th'.
SELECT *
FROM EMPLOYEES
WHERE SALARY>=2000
AND FIRST_NAME LIKE '%th%';

--10)WAQD THOSE EMPLOYEES THERE NAME CANTEND 'ra' AND THERE SALARY UP TO 5000.
SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%ra%' 
AND SALARY >5000;

--11)WAQD DEPARTMENTS THOSE DEPARTMENT ID IS 100,50 AND MANAGER_ID START WITH  3 DEGIT NUMBER.
SELECT * 
FROM DEPARTMENTS
WHERE DEPARTMENT_ID IN (100,50)
AND MANAGER_ID LIKE '___';

--12)WAQD EMPLOYEES ID,FIRST NAME,SALAY,COMMISSION THOSE COMMISSION LESS THAN 0.5 IN DEPARTMENT 80,90,100.
SELECT * 
FROM EMPLOYEES
WHERE COMMISSION_PCT <.5
AND DEPARTMENT_ID IN (80,90,20);

--13)WAQD EMPLOYEES WHOSE EMPLOYEES NOT IN IT_PROG,SA_REP AND SALARY UP TO 4500 AND HIRE GRETER THAN 03-11-2006.
SELECT *
FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG','SA_REP')
AND SALARY >= 4500
AND HIRE_DATE='03-11-2006';

--14)WAQD EMPLOYEES DETEALS WHOSE FIRST NAME, LAST NAME TOTAL CHARECTERS 5 AND SALARY UP TO 3000.
SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_____'
AND LAST_NAME LIKE '_____'
AND SALARY >=3000;

--15)WAQD EMPLOYEES WHOSE SALARY EQUAL TO 7400  AND HIRE DATE HAVING LESS THAN 17-08-02 AND DEPARTMENT NOT IN 100,110 .
SELECT * 
FROM EMPLOYEES
WHERE HIRE_DATE <='17-08-02'
AND DEPARTMENT_ID NOT IN (100,110);

--16)WAQD SHOW THE FULL NAME OF EMPLOYEES AND  HAVING SALARY BETWEEN 10000 TO 17000 AND DEPARTMENT IS 80,90,20.
SELECT (FIRST_NAME||' '||LAST_NAME)AS FULL_NAME,SALARY,DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 17000
AND DEPARTMENT_ID IN(80,90,20);


--17)WQAD EMPLOYEES TO FINED THOSE EMPLOYEES WHERE MANAGER ID 100 AND SALARY IS 
GREATER THAN 7000 AND JOB ID BETWEEN IT PROG,AD VP .
SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID=100
AND SALARY >7000
AND JOB_ID IN('IT_PROG','AD_VP');

--18)WAQD EMPLOYEES DETAILS THIS FORMATE (NEENA IDS 101 IS YOUR MANAGER Steven king)ONLY FOR NEENA EMPLOYEES ID .
SELECT ('Nenna ids 101 is your manager '||EMPLOYEE_ID)
FROM EMPLOYEES
WHERE MANAGER_ID=101;

--19)WAQD DEPARTMENT DETAILS THOSE DEPARTMENT_NAME IS Marketing,IT,Sales THERE LOCATION_ID IN 1700,1400.
SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME IN('Marketing','IT','Sales')
AND LOCATION_ID IN(1800,1400);

--20)WRITE A QUERY TO DISPLAY EMPLOYEES PHONE_NUMBER IN THIS FORMAT(91+9674665690)ONLY IT_PROG AND AD_VP.
SELECT EMPLOYEE_ID,FIRST_NAME,('91+'||PHONE_NUMBER)AS PHONE_NO
FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG','AD_VP'); 

--21)WRITE A QUERY TO DISPLAY EMPLOYEES DETAILS THIS FORMAT('Steven King has 2000 salary')only apply for 
only salary greater than 12000 AND MANGER_ID 100,101.
SELECT (FIRST_NAME||' '||LAST_NAME||' HAS '||SALARY||' SALARY')AS TITAL
FROM EMPLOYEES
WHERE SALARY>12000
AND MANAGER_ID IN (100,101);
 
--22)WRITE A QUERY TO DISPLAY EMPLOYEES DETAILS THIS FORMAT (Steven King IS THE SENIOR EMPLOYEE)ONLY THERE HIRE_DATE IN 01-12-2004,17-08-02;
SELECT (FIRST_NAME||' '||LAST_NAME||' IS THE SENIOR EMPLOYEE')AS SENIOR_EMP 
FROM EMPLOYEES
WHERE HIRE_DATE IN ('01-12-2004','17-08-02'); 


--23)WRITE A QUERY TO DISPLAY EMPLOYEES DETAILS EMPLOYEE_ID,FIRST_NAME,SALARY,SALARY CONVERTING INTO USA DOLLAR($) THERE JOB_ID IS IT_PROG.
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY,(SALARY/89)AS DOLLRS 
FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG','AD_VP'); 

--24)WRITE A QUERY TO DISPLAY EMPLOYEES DETAILS THERE JOB_ID NOT EQUAL TO IT_PROG,FI_ACCOUNT .
SELECT * 
FROM EMPLOYEES 
WHERE JOB_ID NOT IN('IT_PROG','FI_ACCOUNT');

--25)WRITE A QUERY TO SHOW THIS FORMAT(DEPARTMENT 80 HAS 101 IDS EMPLOYEES)WHERE FIST_NAME AS SECOND CHAR AS 'e'.
SELECT ('DEPARTMENT 80 HAS '||EMPLOYEE_ID||' ID,S EMPLOYEES')AS DEPARTMENTS_DETAILS  
FROM EMPLOYEES
WHERE DEPARTMENT_ID=80
AND FIRST_NAME LIKE '_e%'

