--05/01/2026
--SINGLE ROW FUNCTION
--CHARACTER FUNCTION
--CASE MANUPULATION(UPPER,LOWER,INITCAP) , CHARACTER MANUPULATION(CONCAT,INSTR,SUBSTR,LENGTH,LPAD,RPAD,TRIM,REPLACE)
--1)WAQD DETAILS OF EMPLOYEES WORKING IN DEPARTMENT 10, 20, 30 AND LAST_NAME SHOULD BE IN CAPITAL
SELECT FIRST_NAME, UPPER(LAST_NAME) AS LAST_NAME 
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10,20,30);

--2)WAQD EMPLOYEES HAVING FIRST_NAME IN UPPER AND LAST_NAME LOWER WITH SALARY MORE THAN 12000
SELECT UPPER(FIRST_NAME) AS FIRST_NAME, LOWER(LAST_NAME) AS LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 12000;

--3)WAQD EMPLOYEES WHERE FIRST_NAME SHOULD BE CASE SENSITIVE AND LAST_NAME IN UPPER ALONG WITH THEIR JOB_ID
SELECT INITCAP(FIRST_NAME) AS FIRST_NAME , UPPER(LAST_NAME) AS LAST_NAME, JOB_ID
FROM EMPLOYEES ;

--4)WAQD INDIA IN ALL FORMS
SELECT UPPER('INDIA') AS UPPER,LOWER('INDIA') AS LOWER,INITCAP('INDIA')AS INITCAP
FROM DUAL;

--5)WAQD DETAILS OF EMPLOYEES WHERE LAST_NAME SHOULD BE KING
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE UPPER(LAST_NAME) = 'KING';

--6)WAQD DETAILS OF EMPLOYEES FULL_NAME WITH THERE SALARY
SELECT CONCAT(CONCAT(FIRST_NAME,' '), LAST_NAME) AS FULL_NAME , SALARY
FROM EMPLOYEES;

--7)WAQD DETAILS OF EMPLOYEES WHOSE FIRST_NAME INITIAL SHOULD BE KNOWN 
SELECT SUBSTR(FIRST_NAME,1,3) AS DETAIL
FROM EMPLOYEES
ORDER BY FIRST_NAME;

--8)WAQD DETAILS OF EMPLOYEES WHO @ COMES AT WHICH POSITION
SELECT 'SHRADDHA KHAIRNAR' AS FULL_NAME, INSTR('SHRADDHA@GMAIL.COM','@') AS EMAIL FROM DUAL;

--9)WAQD DETAILS OF EMPLOYEES AND FIND THEIR LENGTH OF FIRST NAME WITH THEIR SALARY
SELECT FIRST_NAME,LENGTH(FIRST_NAME)AS FIRST_NAME , SALARY
FROM EMPLOYEES;

--10)WAQD DETAILS OF INDIA USING INSTR
SELECT INSTR('INDIA','I',1,2) AS DETAILS FROM DUAL ;

--11)WAQD DETAILS OF EMPLOYEES WHOSE LAST NAME IS KING SHOULD BE IN UPPER AND LENGTH OF KING
SELECT FIRST_NAME, LAST_NAME, LENGTH(LAST_NAME) AS LAST_NAME
FROM EMPLOYEES
WHERE UPPER(LAST_NAME) = 'KING';

--12)WAQD DETAILS OF EMPLOYEES WHOSE FIRST_NAME A SHOULD BE REPLACE BY @ AND JOB_ID SHOULD BE IT_PROG
SELECT  REPLACE(FIRST_NAME,'A','@') AS FIRST_NAME, LAST_NAME, SALARY, JOB_ID 
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

--13_WAQD DETAILS OF EMPLOYEES WHOSE FIRST_NAME PETER PADDED WITH $ TO THE LEFT TO MAKE IT 10
SELECT LPAD(FIRST_NAME,10,'$') AS FIRST_NAME , LAST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME = 'Peter';

--14)WAQD DETAILS OF EMPLOYEES FIRST_NAME PADDED WITH RPAD TO MAKE IT 10
SELECT RPAD(FIRST_NAME,10,'*') AS FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES 
WHERE (DEPARTMENT_ID =30
OR DEPARTMENT_ID = 40)
AND SALARY >3000;

--15)WAQD DETAILS OF WHERE  LAST_NAME SHOULD BE KOCHHAR IN UPPER AND TRIM IT
SELECT *
FROM EMPLOYEES
WHERE TRIM(UPPER(LAST_NAME)) = 'KOCHHAR' ;

--16)WAQD DETAILS OF NAME WHERE RTRIM A
SELECT (RTRIM('SHRADDHA','A')) AS NAME
FROM DUAL;

--17)WAQD DETAILS OF EMPLOYEE WHERE FULL_NAME SHOULD BE CASE SENSITIVE AND WHOSE NAME START WITH A 
SELECT INITCAP(FIRST_NAME || ' ' || LAST_NAME) AS FULL_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

--18)WAQD DETAILS OF EMPLOYEES FIRST_NAME AND LAST_NAME INITIALS IN UPPER
SELECT UPPER(SUBSTR(FIRST_NAME, 1, 1) || '.' || SUBSTR(last_name, 1, 1)) AS SHORT_NAME, SALARY, JOB_ID, DEPARTMENT_ID
FROM employees;

--19)WAQD DETAILS OF EMPLOYEES FULL_NAME ,SALARY IS MORE THAN 3000 AND HAVING DEPARTMENT_ID 10,20,30,40
SELECT (LPAD(CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME),20,'*')) AS DETAILS, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY >3000
AND DEPARTMENT_ID IN(10,20,30,40);

--20)WAQD DETAILS OF EMPLOYEES FULL NAME IN UPPER , TRIMMED, AND PADDED TO LENGTH 25
SELECT RPAD(TRIM(UPPER(FIRST_NAME || ' ' || LAST_NAME)),25,'*') AS FULL_NAME
FROM EMPLOYEES;

--21)WAQD DETAILS OF EMPLOYEES TO FORMAT THEIR NAMES FOR EMPLOYEES AWARD CERTIFICATE
SELECT INITCAP(CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME)) AS EMP_CERTIFICATE
FROM EMPLOYEES;

--22)WAQD DETAILS OF EMPLOYEES WHOSE FIRST_NAME LENGTH IS LESS THAN OR EQUAL TO 5
SELECT LENGTH(FIRST_NAME) AS LENGTH, FIRST_NAME
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) <= 5;

--23)WAQD DETAILS OF EMPLOYEES WHOSE FIRST_NAME AND LAST_NAME INITIAL WITH SALARY MORE THAN 2000 AND ORDER BY HIRE_DATE
SELECT UPPER(FIRST_NAME || '.' || SUBSTR(LAST_NAME,1,1)) AS LABEL_NAME, HIRE_DATE, JOB_ID, SALARY
FROM EMPLOYEES
WHERE SALARY > 2000
ORDER BY HIRE_DATE;

--24)WAQD TO DETAILS OF EMPLOYEES WHOSE FIRST_NAME AND LAST_NAME STARTS WITH SAME LETTER
SELECT FIRST_NAME ,LAST_NAME 
FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME,1,1) = SUBSTR(LAST_NAME,1,1);

--25)WAQD TO DETAILS OF EMPLOYEES WHERE FIRST_NAME PADDED ON BOTH SIDES TO ALIGN IN REPORTS
SELECT RPAD(LPAD(FIRST_NAME,10,'*'), 15,'*') AS EMP_NAME 
FROM EMPLOYEES;
